<a href="https://colab.research.google.com/github/Sudhar-san24/DataScience-Course/blob/main/Logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error, r2_score

problem statement :to find out weehter person in titanic survived or not

In [93]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

In [94]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [95]:
df = df.drop(columns=['PassengerId'])

In [96]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [97]:
df = df.drop(columns=['Name'])

In [98]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [99]:
df = df.drop(columns=['Ticket'])

In [100]:
df=df.drop(columns=['Cabin'])

In [101]:
df=df.drop(columns=['SibSp'])

In [102]:
df=df.drop(columns=['Parch'])

In [103]:
df

     Survived  Pclass     Sex   Age     Fare Embarked
0           0       3    male  22.0   7.2500        S
1           1       1  female  38.0  71.2833        C
2           1       3  female  26.0   7.9250        S
3           1       1  female  35.0  53.1000        S
4           0       3    male  35.0   8.0500        S
..        ...     ...     ...   ...      ...      ...
886         0       2    male  27.0  13.0000        S
887         1       1  female  19.0  30.0000        S
888         0       3  female   NaN  23.4500        S
889         1       1    male  26.0  30.0000        C
890         0       3    male  32.0   7.7500        Q

[891 rows x 6 columns]

In [104]:
enoder_sex = {'male':0,'female':1}
df['Sex'] =df['Sex'].map(enoder_sex)
df

     Survived  Pclass  Sex   Age     Fare Embarked
0           0       3    0  22.0   7.2500        S
1           1       1    1  38.0  71.2833        C
2           1       3    1  26.0   7.9250        S
3           1       1    1  35.0  53.1000        S
4           0       3    0  35.0   8.0500        S
..        ...     ...  ...   ...      ...      ...
886         0       2    0  27.0  13.0000        S
887         1       1    1  19.0  30.0000        S
888         0       3    1   NaN  23.4500        S
889         1       1    0  26.0  30.0000        C
890         0       3    0  32.0   7.7500        Q

[891 rows x 6 columns]

In [105]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipython-input-694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [106]:
df

     Survived  Pclass  Sex        Age     Fare Embarked
0           0       3    0  22.000000   7.2500        S
1           1       1    1  38.000000  71.2833        C
2           1       3    1  26.000000   7.9250        S
3           1       1    1  35.000000  53.1000        S
4           0       3    0  35.000000   8.0500        S
..        ...     ...  ...        ...      ...      ...
886         0       2    0  27.000000  13.0000        S
887         1       1    1  19.000000  30.0000        S
888         0       3    1  29.699118  23.4500        S
889         1       1    0  26.000000  30.0000        C
890         0       3    0  32.000000   7.7500        Q

[891 rows x 6 columns]

In [107]:
df['Embarked']=df['Embarked'].fillna('S')
encoder_mapping={'S':0,'C':1,'Q':2}
df['Embarked']=df['Embarked'].map(encoder_mapping)

In [108]:
df

     Survived  Pclass  Sex        Age     Fare  Embarked
0           0       3    0  22.000000   7.2500         0
1           1       1    1  38.000000  71.2833         1
2           1       3    1  26.000000   7.9250         0
3           1       1    1  35.000000  53.1000         0
4           0       3    0  35.000000   8.0500         0
..        ...     ...  ...        ...      ...       ...
886         0       2    0  27.000000  13.0000         0
887         1       1    1  19.000000  30.0000         0
888         0       3    1  29.699118  23.4500         0
889         1       1    0  26.000000  30.0000         1
890         0       3    0  32.000000   7.7500         2

[891 rows x 6 columns]

In [109]:
df.head()

   Survived  Pclass  Sex   Age     Fare  Embarked
0         0       3    0  22.0   7.2500         0
1         1       1    1  38.0  71.2833         1
2         1       3    1  26.0   7.9250         0
3         1       1    1  35.0  53.1000         0
4         0       3    0  35.0   8.0500         0

In [110]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [112]:
X

     Pclass  Sex        Age     Fare  Embarked
0         3    0  22.000000   7.2500         0
1         1    1  38.000000  71.2833         1
2         3    1  26.000000   7.9250         0
3         1    1  35.000000  53.1000         0
4         3    0  35.000000   8.0500         0
..      ...  ...        ...      ...       ...
886       2    0  27.000000  13.0000         0
887       1    1  19.000000  30.0000         0
888       3    1  29.699118  23.4500         0
889       1    0  26.000000  30.0000         1
890       3    0  32.000000   7.7500         2

[891 rows x 5 columns]

In [113]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [114]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [115]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 5), (179, 5), (712,), (179,))

In [116]:
891*0.20

178.20000000000002

In [119]:
scaler=StandardScaler()
X_train[['Age','Fare']]=scaler.fit_transform(X_train[['Age','Fare']])
X_test[['Age','Fare']]=scaler.transform(X_test[['Age','Fare']])

In [120]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [121]:
y_prediction=model.predict(X_test)
print('Accuarcy',accuracy_score(y_test,y_prediction))

Accuarcy 0.7932960893854749

In [122]:
confusion_matrix(y_test,y_prediction)

array([[88, 17],
       [20, 54]])

In [123]:
precision_score(y_test,y_prediction)

0.7605633802816901

In [124]:
recall_score(y_test,y_prediction)

0.7297297297297297

In [125]:
f1_score(y_test,y_prediction)

0.7448275862068966

In [136]:
new_data=pd.DataFrame({'Pclass':[1],'Sex':[0],'Age':[30],'Fare':[10],'Embarked':[0]})
new_data[['Age','Fare']]=scaler.transform(new_data[['Age','Fare']])
new_data

   Pclass  Sex       Age      Fare  Embarked
0       1    0  0.035561 -0.434912         0

In [137]:
prediction=model.predict(new_data)
print('Survived' if prediction[0]==1 else 'Not Survived')

Not Survived

In [138]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [139]:
model=KNN(n_neighbors=3)
model.fit(X_train,y_train)
y_prediction=model.predict(X_test)
print('Accuracy',accuracy_score(y_test,y_prediction))

Accuracy 0.8156424581005587

In [142]:
print(precision_score(y_test,y_prediction))
print(recall_score(y_test,y_prediction))
print(f1_score(y_test,y_prediction))

0.8253968253968254
0.7027027027027027
0.7591240875912408

In [143]:
prediction=model.predict(new_data)
print('Survived' if prediction[0]==1 else 'Not Survived')

Not Survived

In [144]:
from sklearn.tree import DecisionTreeClassifier

In [149]:
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_prediction=model.predict(X_test)
print('Accuracy',accuracy_score(y_test,y_prediction))
print(precision_score(y_test,y_prediction))
print(recall_score(y_test,y_prediction))
print(f1_score(y_test,y_prediction))
precision_score(y_test,y_prediction)
prediction=model.predict(new_data)
print('Survived' if prediction[0]==1 else 'Not Survived')

Accuracy 0.776536312849162
0.717948717948718
0.7567567567567568
0.7368421052631579
Not Survived

In [150]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)

RandomForestClassifier()

In [153]:
y_prediction=model.predict(X_test)
print('Accuracy',accuracy_score(y_test,y_prediction))
print(precision_score(y_test,y_prediction))
print(recall_score(y_test,y_prediction))
print(f1_score(y_test,y_prediction))
precision_score(y_test,y_prediction)
prediction=model.predict(new_data)
print('Survived' if prediction[0]==1 else 'Not Survived')

Accuracy 0.8156424581005587
0.7887323943661971
0.7567567567567568
0.7724137931034483
Not Survived